[project]
name = "tiktok-uploader"
version = "0.0.1"
authors = [
  { name="William Kaiser", email="wkaisertexas@gmail.com" },
]
description = "An automatic TikTok video uploader w/ CLI"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[build-system]
requires = [
	"selenium",
	"webdriver_manager"
]

[project.urls]
"Homepage" = "https://github.com/wkaisertexas/tiktok-uploader"
"Bug Tracker" = "https://github.com/wkaisertexas/tiktok-uploader/issues"
