[TikTok Uploader Configuration]
headless = false
quit_on_end = true

implicit_wait = 10 # seconds
explicit_wait = 20 # seconds

[paths]
main = "https://www.tiktok.com/"
login = "https://www.tiktok.com/login/phone-or-email/email"
upload = "https://www.tiktok.com/upload"

[selectors] # Selenium XPATH selectors

	[selectors.login]
	username_field = "//input[@name=\"username\"]"
	password_field = "//input[@type=\"password\"]"
	login_button = "//input[@type=\"submit\""
	
	alert_user_if_failed = true # sends an alert and waits instead of failing
	
	[selectors.upload]
	iframe = "//iframe"
	
	uploadVideo = "//input[@type=\"file\"]"
	uploadConfirmation = "//div[.=\"Change video\"]" 
	
	description = "//div[@contenteditable=\"true\""

	post = "//button[.=\"Post\"]"
	postConfirmation = "//div[.=\"Your video is being uploaded to TikTok!\"]"

[defaults]
headless = false
quit_on_end = true

implicit_wait = 10 # seconds
explicit_wait = 20 # seconds
